### ISSUE TITLE
Приложение с чатом падает при включенной обфускации

### ISSUE THREAD

**Issue by Sash0k** [crafttalk/crafttalk-android-sdk#10]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.gson.j.f()' on a null object reference
        at com.crafttalk.chat.data.local.db.entity.deserializers.TagDeserializer.a(TagDeserializer.kt:6)
        at com.crafttalk.chat.data.local.db.entity.deserializers.TagDeserializer.deserialize(TagDeserializer.kt:1)
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:5)
        at com.google.gson.Gson.i(Gson.java:6)
        at com.google.gson.Gson.k(Gson.java:2)
        at com.google.gson.Gson.m(Gson.java:2)
        at e5.c.b(SpanStructureListConverter.kt:6)
        at c5.d$c$a.q(MessagesDao_Impl.java:43)
        at g1.a.l(LimitOffsetDataSource.java:9)
```

подробней:
```
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.gson.JsonElement.getAsString()' on a null object reference
    	at com.crafttalk.chat.data.local.db.entity.deserializers.TagDeserializer.deserialize(TagDeserializer.kt:13)
    	at com.crafttalk.chat.data.local.db.entity.deserializers.TagDeserializer.deserialize(TagDeserializer.kt:7)
    	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
    	at com.google.gson.Gson.fromJson(Gson.java:991)
    	at com.google.gson.Gson.fromJson(Gson.java:956)
    	at com.google.gson.Gson.fromJson(Gson.java:905)
    	at com.crafttalk.chat.data.local.db.entity.converters.SpanStructureListConverter.toSpanStructureList(SpanStructureListConverter.kt:48)
    	at com.crafttalk.chat.data.local.db.dao.MessagesDao_Impl$12$1.convertRows(MessagesDao_Impl.java:817)
```

**Comment by Sash0k** [comment]
проблема состоит в том, что обфускатор переименовывает типы данных, и затем они некорректно записываются в sqlite. Далее при парсинге приложение падает.

пример валидных данных:
```
[
{"countNesting":0,"pointEnd":212,"pointStart":51,"name":"ul"},
{"countNesting":0,"pointEnd":77,"pointStart":52,"name":"li"}
]
```
так это сохраняется с обфускацией:
```
[
{"d":51,"e":212,"f":0,"a":"ul"},
{"d":52,"e":77,"f":0,"a":"li"}
]
```
исправлением будет настройка исключений в правилах proguard
