### ISSUE TITLE
Crash при открытии диалога с картинкой

### ISSUE THREAD

**Issue by srgpanov** [crafttalk/crafttalk-android-sdk#24]
Здравствуйте. 
Прошу починить баг. 
Если этому багу будет присвоен низкий приоритет, могу подготовить pull request c правками.

**Сценарий вопроизвидения:**

1. Добавить картинку в чат.
2. Поменять конфигурацию устройства. (Повернуть телефон в горизонтальный режим/изменить способ навигации в системе/сменить язык..) 
3. Нажать на добавленную картинку в чат

**Ожидаемый результат:**
Открывается полноэкранный диалог с картинкой

**Фиксированый результат:**
Приложение крашится.

Версия библиотеки:**1.2.41.2.0**

```
FATAL EXCEPTION: main
                                   Process: com.crafttalk.sampleChat, PID: 29203
                                   java.lang.IllegalArgumentException: You cannot start a load for a destroyed activity
                                   	at com.bumptech.glide.manager.RequestManagerRetriever.assertNotDestroyed(RequestManagerRetriever.java:353)
                                   	at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:153)
                                   	at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:133)
                                   	at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:141)
                                   	at com.bumptech.glide.Glide.with(Glide.java:818)
                                   	at com.crafttalk.chat.presentation.feature.view_picture.ShowImageDialog.onCreate(ShowMediaDialog.kt:134)
                                   	at android.app.Dialog.dispatchOnCreate(Dialog.java:424)
                                   	at android.app.Dialog.show(Dialog.java:318)
                                   	at com.crafttalk.chat.presentation.feature.view_picture.ShowImageDialog$Builder.show(ShowMediaDialog.kt:111)
                                   	at com.crafttalk.chat.presentation.ChatViewModel.openImage(ChatViewModel.kt:271)
                                   	at com.crafttalk.chat.presentation.ChatView$setListMessages$2.invoke(ChatView.kt:422)
                                   	at com.crafttalk.chat.presentation.ChatView$setListMessages$2.invoke(ChatView.kt:422)
                                   	at com.crafttalk.chat.presentation.adapters.AdapterListMessages$onCreateViewHolder$1.invoke(AdapterListMessages.kt:35)
                                   	at com.crafttalk.chat.presentation.adapters.AdapterListMessages$onCreateViewHolder$1.invoke(AdapterListMessages.kt:35)
                                   	at com.crafttalk.chat.presentation.holders.HolderUserImageMessage.onClick(HolderUserImageMessage.kt:48)
                                   	at android.view.View.performClick(View.java:7441)
                                   	at android.view.View.performClickInternal(View.java:7418)
                                   	at android.view.View.access$3700(View.java:835)
                                   	at android.view.View$PerformClick.run(View.java:28676)
                                   	at android.os.Handler.handleCallback(Handler.java:938)
                                   	at android.os.Handler.dispatchMessage(Handler.java:99)
                                   	at android.os.Looper.loopOnce(Looper.java:201)
                                   	at android.os.Looper.loop(Looper.java:288)
                                   	at android.app.ActivityThread.main(ActivityThread.java:7842)
                                   	at java.lang.reflect.Method.invoke(Native Method)
                                   	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                   	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by srgpanov** [comment]
https://github.com/crafttalk/crafttalk-android-sdk/assets/19637857/d458743d-9ca3-4576-88a7-03fdb011ec6f
